//! # csvranger
//! csranger Rust library for parsing the output CSV files of [10x Genomics *ranger pipelines](https://www.10xgenomics.com/software).
//!
//! Many of 10x Genomics data-processing pipelines produce CSV files that summarize the data. These CSVs, while human-readable, cannot be parsed by a machine without extra effort. This small crate provides the necessary functionality to parse the values in these files. See documentation at [csvranger](https://docs.rs/csvranger).
//! ## Example usage
//!
//! ### Using `TenxCsvValue::from_csv_value`
//! ```
//! use csvranger::TenxCsvValue;
//!
//! fn main() {
//!     // Sample data from test-data/cellranger_multi.10.0
//!     let raw_csv = b"Sample ID,Sample barcodes,Sample description,GEX: Cells,GEX: Confidently mapped reads in cells,GEX: Median UMI counts per cell,GEX: Median genes per cell,GEX: Total genes detected
//!     SOD1_G93A_mouse_spinal_cord_P112_specimen_1,,SOD1-G93A mouse spinal cord from P112 mouse,16410,0.6847850295990157,2244,1305,27219";
//!
//!     let mut reader = csv::Reader::from_reader(&raw_csv[..]);
//!     for line in reader.records() {
//!         // Don't actually call .unwrap in production!
//!         let line = line.unwrap();
//!         for value in line.iter() {
//!             // This is where the magic happens
//!             TenxCsvValue::from_csv_value(value);
//!         }
//!     }
//! }
//! ```
//!
//! ### Deserializing directly
//! ```
//! use csvranger::TenxCsvValue;
//! use std::collections::HashMap;
//!
//! fn main() {
//!     // Sample data from test-data/cellranger_multi.10.0
//!     let raw_csv = b"Sample ID,Sample barcodes,Sample description,GEX: Cells,GEX: Confidently mapped reads in cells,GEX: Median UMI counts per cell,GEX: Median genes per cell,GEX: Total genes detected
//!     SOD1_G93A_mouse_spinal_cord_P112_specimen_1,,SOD1-G93A mouse spinal cord from P112 mouse,16410,0.6847850295990157,2244,1305,27219";
//!
//!     let mut reader = csv::Reader::from_reader(&raw_csv[..]);
//!     let mut parsed_data: Vec<HashMap<String, TenxCsvValue>> = Vec::new();
//!
//!     #[cfg(feature = "serde")]
//!     for deserialized_record in reader.deserialize() {
//!         parsed_data.push(deserialized_record.unwrap())
//!     }
//! }
//! ```
use std::str::FromStr;

#[cfg(feature = "legacy")]
pub use legacy::{parse_legacy_csv_value_as_f64, parse_legacy_csv_value_as_i64};

#[cfg(feature = "legacy")]
mod legacy;

/// A CSV value found in the `metrics_summary.csv` files produced by 10x
/// Genomics *ranger pipelines.
///
/// If parsing a whole CSV at once, it's useful to have one `enum` that can fit
/// any of the values in the file. If you only need a specific field in the file
/// with a known numeric type, you may want to deserialize it directly or use
/// [`parse_legacy_csv_value_as_f64`] and/or [`parse_legacy_csv_value_as_i64`]
/// if dealing with outputs generated by older pipelines.
#[derive(Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
#[cfg_attr(
    all(feature = "serde", not(feature = "legacy")),
    derive(serde::Deserialize)
)]
#[cfg_attr(feature = "schemars", derive(schemars::JsonSchema))]
#[cfg_attr(feature = "serde", serde(untagged))]
pub enum TenxCsvValue {
    F64(f64),
    I64(i64),
    String(String),
}

impl std::fmt::Display for TenxCsvValue {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::F64(v) => v.fmt(f),
            Self::I64(v) => v.fmt(f),
            Self::String(v) => v.fmt(f),
        }
    }
}

#[cfg(not(feature = "legacy"))]
impl From<&str> for TenxCsvValue {
    fn from(value: &str) -> Self {
        Self::from_csv_value(value)
    }
}

#[cfg(not(feature = "legacy"))]
impl std::str::FromStr for TenxCsvValue {
    type Err = std::convert::Infallible;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Ok(Self::from(s))
    }
}

impl TenxCsvValue {
    /// Parse a value from a CSV produced by a modern *ranger pipeline.
    ///
    /// If the CSV-file was generated using any of the following, use
    /// [`TenxCsvValue::from_legacy_csv_value`] instead to correctly extract
    /// numerical values (you will need to activate the `legacy` feature):
    /// - `cellranger count < 10`
    /// - `cellranger multi < 10`
    ///
    /// If the CSV-file was generated using any of the following:
    /// - `cellranger count >= 10`
    /// - `cellranger multi >= 10`
    /// - `cellranger-atac count >= 2`
    /// - `spaceranger count >= 4`
    ///
    /// then this is the correct method. Note that
    /// [`TenxCsvValue::from_legacy_csv_value`] will still work for modern
    /// pipelines, but because it uses a regular expression for parsing, it will
    /// be less performant. Note also that other versions of `spaceranger` and
    /// `cellranger-atac` may produce outputs compatible with this method, but
    /// they are currently untested.
    pub fn from_csv_value(val: &str) -> Self {
        i64::from_str(val)
            .ok()
            .map(Self::I64)
            .or_else(|| f64::from_str(val).ok().map(Self::F64))
            .unwrap_or_else(|| Self::String(val.to_owned()))
    }

    pub fn is_f64(&self) -> bool {
        matches!(self, Self::F64(_))
    }

    pub fn is_i64(&self) -> bool {
        matches!(self, Self::I64(_))
    }

    pub fn is_string(&self) -> bool {
        matches!(self, Self::String(_))
    }

    pub fn as_f64(&self) -> Option<f64> {
        match self {
            Self::F64(f) => Some(*f),
            _ => None,
        }
    }

    pub fn as_i64(&self) -> Option<i64> {
        match self {
            Self::I64(i) => Some(*i),
            _ => None,
        }
    }

    pub fn as_str(&self) -> Option<&str> {
        match self {
            Self::String(s) => Some(s),
            _ => None,
        }
    }
}

#[cfg(test)]
pub mod tests {
    use crate::TenxCsvValue;

    pub fn read_singlerow_csv(
        raw_csv: &[u8],
        parse_fn: impl Fn(&str) -> TenxCsvValue,
    ) -> Vec<TenxCsvValue> {
        let mut reader = csv::Reader::from_reader(raw_csv);
        let line = reader.records().collect::<Result<Vec<_>, _>>().unwrap();

        assert_eq!(line.len(), 1);

        line[0].iter().map(parse_fn).collect()
    }

    pub fn read_multirow_csv(
        raw_csv: &[u8],
        parse_fn: impl Fn(&str) -> TenxCsvValue,
    ) -> Vec<TenxCsvValue> {
        let mut parsed_data = Vec::with_capacity(50);

        let mut reader = csv::Reader::from_reader(raw_csv);
        for line in reader.records() {
            let line = line.unwrap();
            let raw_val = line.get(5).unwrap();
            parsed_data.push(parse_fn(raw_val));
        }

        parsed_data
    }

    fn read_modern_singlerow_csv(raw_csv: &[u8]) -> Vec<TenxCsvValue> {
        read_singlerow_csv(raw_csv, TenxCsvValue::from_csv_value)
    }

    fn read_modern_multirow_csv(raw_csv: &[u8]) -> Vec<TenxCsvValue> {
        read_multirow_csv(raw_csv, TenxCsvValue::from_csv_value)
    }

    #[test]
    fn cellranger_multi_10_qc_library_metrics() {
        let raw_data = include_bytes!(
            "../test-data/cellranger_multi.10.0/\
             SOD1_G93A_mouse_spinal_cord_P112_specimen_1_Multiplex_qc_library_metrics.csv"
        );

        let parsed_data = read_modern_multirow_csv(&raw_data[..]);
        let expected_data = vec![
            TenxCsvValue::I64(321950603),
            TenxCsvValue::F64(0.9754667347931396),
            TenxCsvValue::F64(0.9838510115040644),
            TenxCsvValue::F64(0.9810434401949358),
            TenxCsvValue::I64(16410),
            TenxCsvValue::F64(0.18127985925840928),
            TenxCsvValue::F64(0.6847850295990157),
            TenxCsvValue::F64(0.39215314033749454),
            TenxCsvValue::F64(0.9176445866138042),
            TenxCsvValue::F64(0.07506513662283776),
            TenxCsvValue::F64(0.4504263096534719),
            TenxCsvValue::F64(0.657908592269355),
            TenxCsvValue::F64(0.945846350845319),
            TenxCsvValue::I64(19619),
            TenxCsvValue::I64(321950603),
            TenxCsvValue::I64(321950603),
            TenxCsvValue::F64(0.4625052256865317),
            TenxCsvValue::F64(0.9984212981890268),
            TenxCsvValue::F64(0.8701900924844672),
        ];

        assert_eq!(parsed_data, expected_data);
    }

    #[test]
    fn cellranger_multi_10_metrics_summary() {
        let raw_data = include_bytes!(
            "../test-data/cellranger_multi.10.0/SOD1_G93A_mouse_spinal_cord_P112_specimen_1_SOD1_G93A_mouse_spinal_cord_P112_specimen_1_metrics_summary.csv"
        );

        let parsed_data = read_modern_multirow_csv(&raw_data[..]);
        let expected_data = vec![
            TenxCsvValue::I64(16410),
            TenxCsvValue::F64(0.6847850295990157),
            TenxCsvValue::I64(2244),
            TenxCsvValue::I64(1305),
            TenxCsvValue::I64(27219),
            TenxCsvValue::I64(321950603),
            TenxCsvValue::F64(0.9754667347931396),
            TenxCsvValue::F64(0.9838510115040644),
            TenxCsvValue::F64(0.9810434401949358),
            TenxCsvValue::I64(16410),
            TenxCsvValue::F64(0.18127985925840928),
            TenxCsvValue::F64(0.6847850295990157),
            TenxCsvValue::F64(0.39215314033749454),
            TenxCsvValue::F64(0.9176445866138042),
            TenxCsvValue::F64(0.07506513662283776),
            TenxCsvValue::F64(0.4504263096534719),
            TenxCsvValue::F64(0.657908592269355),
            TenxCsvValue::F64(0.945846350845319),
            TenxCsvValue::I64(19619),
            TenxCsvValue::I64(321950603),
            TenxCsvValue::I64(321950603),
            TenxCsvValue::F64(0.4625052256865317),
            TenxCsvValue::F64(0.9984212981890268),
            TenxCsvValue::F64(0.8701900924844672),
        ];

        assert_eq!(parsed_data, expected_data);
    }

    #[test]
    fn cellranger_atac_count_2_summary() {
        let raw_data = include_bytes!(
            "../test-data/cellranger-atac_count.2.1/\
             8k_mouse_cortex_ATACv2_nextgem_Chromium_X_summary.csv"
        );

        let parsed_data = read_modern_singlerow_csv(&raw_data[..]);
        let expected_data = vec![
            TenxCsvValue::String("8k_mouse_cortex_ATACv2_nextgem_Chromium_X".to_owned()),
            TenxCsvValue::String("mm10".to_owned()),
            TenxCsvValue::String("cellranger-atac-2.1.0".to_owned()),
            TenxCsvValue::I64(8067),
            TenxCsvValue::F64(0.8662),
            TenxCsvValue::F64(455615555.4000),
            TenxCsvValue::F64(0.7176),
            TenxCsvValue::F64(0.1905),
            TenxCsvValue::F64(0.0554),
            TenxCsvValue::F64(0.9310),
            TenxCsvValue::F64(0.2408),
            TenxCsvValue::F64(0.4371),
            TenxCsvValue::F64(0.4051),
            TenxCsvValue::F64(0.3878),
            TenxCsvValue::F64(0.4537),
            TenxCsvValue::F64(56288.3711),
            TenxCsvValue::F64(24552.0000),
            TenxCsvValue::F64(0.1211),
            TenxCsvValue::I64(177224),
            TenxCsvValue::F64(0.3304),
            TenxCsvValue::F64(0.8805),
            TenxCsvValue::F64(0.9447),
            TenxCsvValue::F64(0.9324),
            TenxCsvValue::F64(0.8781),
            TenxCsvValue::I64(454078290),
            TenxCsvValue::F64(0.4666),
            TenxCsvValue::F64(10.0386),
            TenxCsvValue::F64(0.0095),
            TenxCsvValue::F64(0.9555),
        ];

        assert_eq!(parsed_data, expected_data);
    }

    #[test]
    fn spaceranger_count_4_metrics_summary() {
        let raw_data = include_bytes!(
            "../test-data/spaceranger_count.4.1/Visium_HD_11mm_Human_TA_metrics_summary.csv"
        );

        let parsed_data = read_modern_singlerow_csv(&raw_data[..]);
        let expected_data = vec![
            TenxCsvValue::String("Visium_HD_11mm_Human_TA".to_owned()),
            TenxCsvValue::I64(905003210),
            TenxCsvValue::F64(0.9070668710666784),
            TenxCsvValue::F64(0.9983401252245282),
            TenxCsvValue::F64(0.7098832774542063),
            TenxCsvValue::F64(0.9737220789750496),
            TenxCsvValue::F64(0.9629752017438916),
            TenxCsvValue::F64(0.963444161020736),
            TenxCsvValue::F64(0.9807111314002964),
            TenxCsvValue::F64(0.9755059454430002),
            TenxCsvValue::F64(0.9886539693144586),
            TenxCsvValue::I64(18074),
            TenxCsvValue::F64(0.9509161729934638),
            TenxCsvValue::I64(18085),
            TenxCsvValue::F64(0.003445940263570999),
            TenxCsvValue::F64(0.001759245693725219),
            TenxCsvValue::F64(0.008983033710603426),
            TenxCsvValue::F64(42.0),
            TenxCsvValue::I64(20352930),
            TenxCsvValue::F64(44.46550005330928),
            TenxCsvValue::F64(0.6669904245105683),
            TenxCsvValue::F64(10.316071346974791),
            TenxCsvValue::F64(10.530010814168334),
            TenxCsvValue::I64(18074),
            TenxCsvValue::I64(1290617),
            TenxCsvValue::F64(701.2174874498012),
            TenxCsvValue::F64(0.6767215772554074),
            TenxCsvValue::F64(148.7440216578619),
            TenxCsvValue::F64(166.5460860968123),
            TenxCsvValue::I64(18074),
            TenxCsvValue::F64(2602282.5952626923),
            TenxCsvValue::F64(9853515.53268708),
            TenxCsvValue::I64(328840),
            TenxCsvValue::F64(2752.1080464663664),
            TenxCsvValue::F64(0.6886975607406368),
            TenxCsvValue::F64(511.74513441186934),
            TenxCsvValue::F64(654.9548868750757),
            TenxCsvValue::I64(18074),
            TenxCsvValue::I64(506400),
            TenxCsvValue::F64(0.8),
            TenxCsvValue::F64(0.8654),
            TenxCsvValue::F64(1394.6),
            TenxCsvValue::F64(181.0),
            TenxCsvValue::F64(202.0),
            TenxCsvValue::F64(116.0),
            TenxCsvValue::F64(28.0),
            TenxCsvValue::I64(256),
            TenxCsvValue::F64(0.27228000754439524),
        ];

        assert_eq!(parsed_data, expected_data);
    }
}
