name: Check Rust Code
on:
  push:
    paths:
      - "**/*.rs"

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -Dwarnings

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Cache cargo files
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          cache-on-failure: true

      - name: Lint
        run: cargo clippy --all-features

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Cache cargo files
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          cache-workspace-crates: true
          cache-on-failure: true

      - name: Install nightly toolchain
        # This is updated weekly-ish
        run: rustup component add --toolchain nightly-2026-03-09 rustfmt

      - name: Format
        run: cargo +nightly-2026-03-09 fmt -- --check

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Cache cargo files
        uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          cache-workspace-crates: true

      - name: Test
        run: cargo test --all-features
